# Documentation: https://kubernetes.io/docs/concepts/services-networking/service/
{{- if .Values.Service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- include "helm-echoserver-chart.labels" . | indent 2 }}
spec:
  ports:
    # port is what this service should serve on, and targetPort is the port in the container.
    - port: {{ .Values.Service.Port }}
      name: helm-echoserver-main
      targetPort: {{ .Values.ContainerPort }}
      protocol: {{ .Values.Service.Protocol }}

  # ClusterIP is the default.
  type: {{ .Values.Service.Type | default "ClusterIP" }}
  selector:
    {{ include "app-unique-selector-label" . }}
{{- end }}
